### ISSUE TITLE
perf(todo): Merge hot updates of uno.css to reduce the number of updates

### ISSUE THREAD

**Issue by Simon-He95** [unocss/unocss#3775]
### Clear and concise description of the problem

Every time the file magicString is updated, it will trigger a hot update of uno.css. Is it possible to find a way to merge this update, or add a delay or cancellation strategy, and only update it once for the last time?

### Suggested solution

To be explored

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We already doing a bit of throttling for sending the events. If too long it would make it feel slower to response to user changes. Do you have some case specifically to improve?

**Comment by Simon-He95** [comment]
#3741
